<?php

/**
 * @file
 * Functions to support theming in the finenothings theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function finenothings_preprocess_html(array &$variables) {

}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function finenothings_preprocess_page(array &$variables) {

}

/**
 * Implements hook_preprocess_form().
 */
function finenothings_preprocess_form(array &$variables) {

}
